### ISSUE TITLE
Pair history organized by team members

### ISSUE THREAD

**Issue by fzondlo** [fzondlo/peartrix#4]
Pair history right now is a bit of a mess, needs to be cleaned up.

**Comment by risu-kun** [comment]
Hey @fzondlo, I'll pick this up if you like; do you guys have any specific ideas of how you'd like the page to be organized? :)

**Comment by fzondlo** [comment]
I think this is good to close thanks to awesome work by @risu-kun 

Reopen at will if you think we're missing anything here.
